spring:
  application:
    name: consumer-message
server:
  port: 9600
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka/